<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>AED Hallucinations - The Decoder Knows Too – Piotr Zulawski</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-f670ab49fb9634e9dab58972b11477cb.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Piotr Zulawski</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../cycling/index.html"> 
<span class="menu-text">Cycling</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="../../machine-learning/index.html" aria-current="page"> 
<span class="menu-text">Machine Learning</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../machine-learning/gamedev/cometa.html"> 
<span class="menu-text">Game Development</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../other/cycling-data-analysis.html"> 
<span class="menu-text">Other</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../bookshelf.html"> 
<span class="menu-text">Bookshelf</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../machine-learning/ml/aed-hallucination-probe.html">Hearing Things</a></li><li class="breadcrumb-item"><a href="../../machine-learning/ml/aed-hallucination-decoder.html">AED Hallucinations - The Decoder Knows Too</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Machine Learning</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#" role="navigation" aria-expanded="true">
 <span class="menu-text">Hearing Things</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/ml/aed-hallucination-probe.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Where Do AED Hallucinations Come From?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/ml/aed-hallucination-intervention.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AED Hallucinations - Causal Intervention</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/ml/aed-hallucination-decoder.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">AED Hallucinations - The Decoder Knows Too</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#" role="navigation" aria-expanded="true">
 <span class="menu-text">GPT Adventures</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/ml/gpt-adventures/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">GPT Adventures</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/ml/gpt-adventures/phase1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">GPT Adventures — Part 1: Baseline Implementation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/ml/gpt-adventures/phase2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part 2 - Profiling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/ml/gpt-adventures/phase3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase 3</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/ml/gpt-adventures/phase4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">GPT Adventures — Part 4: Distribute It</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/ml/neural-net-from-scratch.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">A Neural Net From Scratch</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/ml/corneal-endothelium.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Corneal Endothelium Image Processing</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/ml/gans.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Image Generation with GANs</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/ml/better-gans.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Better GANs - Gradient Penalisation</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#method" id="toc-method" class="nav-link active" data-scroll-target="#method">Method</a>
  <ul class="collapse">
  <li><a href="#held-out-evaluation" id="toc-held-out-evaluation" class="nav-link" data-scroll-target="#held-out-evaluation">Held-out evaluation</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a>
  <ul class="collapse">
  <li><a href="#the-decoder-also-separates" id="toc-the-decoder-also-separates" class="nav-link" data-scroll-target="#the-decoder-also-separates">The decoder also separates</a></li>
  <li><a href="#held-out-evaluation-98-recall-95-precision" id="toc-held-out-evaluation-98-recall-95-precision" class="nav-link" data-scroll-target="#held-out-evaluation-98-recall-95-precision">Held-out evaluation: 98% recall, 95% precision</a></li>
  <li><a href="#the-errors" id="toc-the-errors" class="nav-link" data-scroll-target="#the-errors">The errors</a></li>
  <li><a href="#where-the-signal-lives-cross-attention-not-generation" id="toc-where-the-signal-lives-cross-attention-not-generation" class="nav-link" data-scroll-target="#where-the-signal-lives-cross-attention-not-generation">Where the signal lives: cross-attention, not generation</a></li>
  <li><a href="#ablation-ruling-out-sequence-length-confounds" id="toc-ablation-ruling-out-sequence-length-confounds" class="nav-link" data-scroll-target="#ablation-ruling-out-sequence-length-confounds">Ablation: ruling out sequence-length confounds</a></li>
  </ul></li>
  <li><a href="#interpretation" id="toc-interpretation" class="nav-link" data-scroll-target="#interpretation">Interpretation</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../machine-learning/ml/aed-hallucination-probe.html">Hearing Things</a></li><li class="breadcrumb-item"><a href="../../machine-learning/ml/aed-hallucination-decoder.html">AED Hallucinations - The Decoder Knows Too</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">AED Hallucinations - The Decoder Knows Too</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>In the <a href="../../machine-learning/ml/aed-hallucination-probe.html">previous articles</a>, we established two things: the encoder of our AED model builds a near-perfect linear representation of speech vs non-speech from the very first transformer layer, and - crucially - this representation is causally upstream of the decoder. Steering encoder activations along the probe direction suppresses approximately 50% of hallucinations on non-speech audio, without measurably degrading transcription of real speech. <strong>Case A is confirmed</strong>: the model knows it is looking at non-speech; it simply fails to act on that knowledge.</p>
<p>This raises a natural follow-on question. When the decoder generates a hallucinated transcript - token by token, producing “Oh,” or “Thank you.” from ambient noise - does it build an internal representation of what it is doing? Does it, at the point of generation, “know” that it is hallucinating?</p>
<p>This is a distinct question from the encoder probe. The encoder is processing audio; we are asking whether the acoustic features it builds distinguish the two classes. Here, we are asking about the decoder’s state during generation - whether the hidden representations it constructs while producing output differ between hallucination and real transcription. The answer would tell us whether the failure to suppress hallucinations is isolated to the encoder-decoder interface, or whether it runs all the way through to the output stage.</p>
<section id="method" class="level2">
<h2 class="anchored" data-anchor-id="method">Method</h2>
<p>The method is identical in structure to the encoder probe, applied to the decoder layers. We register forward hooks on each decoder transformer layer during beam search. At each generation step, the new token’s hidden state is captured - with key-value caching enabled, each step processes exactly one new token, so the hook fires once per step and records a <code>(hidden_dim,)</code> vector. These are mean-pooled over the generated sequence to give one vector per example per layer.</p>
<p>The two classes are:</p>
<ul>
<li><strong>Hallucination</strong> (<code>y = 0</code>): non-speech audio where the model produced non-empty output</li>
<li><strong>Normal</strong> (<code>y = 1</code>): speech audio where the model produced a transcript</li>
</ul>
<p>A logistic regression is trained per decoder layer, and 5-fold cross-validation gives unbiased accuracy estimates.</p>
<p>One subtlety: for non-speech audio, many segments produce no output at all - silence segments that the model correctly transcribes as silent. These contribute nothing to the hallucination class, since there is no decoder activation to probe. The collection therefore only retains examples where the model actually generated output, ensuring we are probing the decoder’s state during active hallucination rather than measuring the (trivially separable) difference between “generated something” and “generated nothing”.</p>
<section id="held-out-evaluation" class="level3">
<h3 class="anchored" data-anchor-id="held-out-evaluation">Held-out evaluation</h3>
<p>The collection loop tracks how many entries were scanned before the training set was filled. All entries beyond that scan boundary are held out and form a clean test set, guaranteed to have never been processed during training. This avoids any risk of leakage from examples that were scanned but discarded (e.g.&nbsp;non-hallucinating non-speech segments). The eval loop runs on this fully disjoint slice.</p>
</section>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">Results</h2>
<section id="the-decoder-also-separates" class="level3">
<h3 class="anchored" data-anchor-id="the-decoder-also-separates">The decoder also separates</h3>
<p>One important difference from the encoder probe is the choice of training data. The encoder probe used pure silence segments - acoustically unambiguous non-speech - against dense, fluent speech. The decoder probe here uses a harder, more realistic setting: the non-speech class consists of <strong>sparse speech segments</strong> - real audio containing speech interrupted by long pauses, background noise, and extended non-speech passages. These are exactly the segments most likely to cause hallucinations in production, and they represent the worst case for linear separability. The goal is to establish whether the separation holds even when the acoustic boundary between speech and non-speech is genuinely ambiguous.</p>
<p>The curve is essentially flat at above 0.96 across all decoder layers, peaking at 0.972 at layer 6. Like the encoder, the distinction is present from the very first layer and does not materially change with depth — the signal is immediately accessible and remains so throughout the full decoder stack.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../../images/ml/decoder-probe-accuracy.png" class="img-fluid figure-img"></p>
<figcaption>Probe accuracy across decoder layers, trained on sparse speech vs hallucination. The curve is flat above 0.96 throughout, peaking at 0.972 at layer 6.</figcaption>
</figure>
</div>
<p>The 1D projection at the best layer shows essentially complete separation, with a gap of 5.46 pooled standard deviations between the two class centres.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../../images/ml/decoder-probe-direction-viz.png" class="img-fluid figure-img"></p>
<figcaption>Left: 1D projection of all examples onto the probe direction. Hallucination (blue) and normal transcription (red) are cleanly separated. Right: PCA scatter at the same layer, with ambiguous-zone examples highlighted (gold diamonds) - borderline cases corresponding to single punctuation marks and very short fragments.</figcaption>
</figure>
</div>
</section>
<section id="held-out-evaluation-98-recall-95-precision" class="level3">
<h3 class="anchored" data-anchor-id="held-out-evaluation-98-recall-95-precision">Held-out evaluation: 98% recall, 95% precision</h3>
<p>The fitted probe is evaluated on the held-out test set as a runtime hallucination detector: run the model, collect decoder activations, classify without looking at the transcript output.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Correct</th>
<th style="text-align: right;">Errors</th>
<th style="text-align: right;">Rate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Non-speech hallucinations</td>
<td style="text-align: right;">482 detected</td>
<td style="text-align: right;">12 missed</td>
<td style="text-align: right;"><strong>recall 0.98</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;">Speech transcriptions</td>
<td style="text-align: right;">871 passed</td>
<td style="text-align: right;">23 false positives</td>
<td style="text-align: right;"><strong>precision 0.95</strong></td>
</tr>
</tbody>
</table>
<p>Of 494 hallucinating segments in the test set, 482 are correctly identified. Of 894 normal speech segments, 871 are correctly cleared. 35 cases in total appear as errors. The correctly detected hallucinations are characteristic of the failure mode: short, affirmative-sounding fragments produced from ambient silence - <em>“Oh,”</em>, <em>“Hold on.”</em>, <em>“Thank you.”</em>, <em>“I’m gonna go with it.”</em>, <em>“Jesus.”</em> - consistent with what was observed in the encoder steering experiments.</p>
</section>
<section id="the-errors" class="level3">
<h3 class="anchored" data-anchor-id="the-errors">The errors</h3>
<p>The 12 false negatives are non-speech segments that contain audible speech, where the model produces a coherent-sounding transcript and the probe correctly classifies it as normal transcription — the label is inconsistent with the audio content. The hallucinated token fractions are correspondingly low (0.00–0.56), in contrast to genuine hallucinations where the prefix and, most frequently, all tokens are classified as hallucinations.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Model output</th>
<th>Hallucinated token fraction</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><em>I just…</em></td>
<td>0.50</td>
<td><audio controls="" style="height:1.4em;width:160px"><source src="../../audio/ml/fn-01.wav" type="audio/wav"></audio></td>
</tr>
<tr class="even">
<td><em>Right here.</em></td>
<td>0.50</td>
<td><audio controls="" style="height:1.4em;width:160px"><source src="../../audio/ml/fn-02.wav" type="audio/wav"></audio></td>
</tr>
<tr class="odd">
<td><em>about it.</em></td>
<td>0.25</td>
<td><audio controls="" style="height:1.4em;width:160px"><source src="../../audio/ml/fn-03.wav" type="audio/wav"></audio></td>
</tr>
<tr class="even">
<td><em>I don’t know why I always just.</em></td>
<td>0.27</td>
<td><audio controls="" style="height:1.4em;width:160px"><source src="../../audio/ml/fn-04.wav" type="audio/wav"></audio></td>
</tr>
<tr class="odd">
<td><em>Well, and, um…</em></td>
<td>0.29</td>
<td><audio controls="" style="height:1.4em;width:160px"><source src="../../audio/ml/fn-05.wav" type="audio/wav"></audio></td>
</tr>
<tr class="even">
<td><em>Any</em></td>
<td>0.50</td>
<td><audio controls="" style="height:1.4em;width:160px"><source src="../../audio/ml/fn-06.wav" type="audio/wav"></audio></td>
</tr>
<tr class="odd">
<td><em>And Janet, what the…</em></td>
<td>0.56</td>
<td><audio controls="" style="height:1.4em;width:160px"><source src="../../audio/ml/fn-07.wav" type="audio/wav"></audio></td>
</tr>
<tr class="even">
<td><em>Oh.</em></td>
<td>0.33</td>
<td><audio controls="" style="height:1.4em;width:160px"><source src="../../audio/ml/fn-08.wav" type="audio/wav"></audio></td>
</tr>
<tr class="odd">
<td><em>We are taking.</em></td>
<td>0.40</td>
<td><audio controls="" style="height:1.4em;width:160px"><source src="../../audio/ml/fn-09.wav" type="audio/wav"></audio></td>
</tr>
<tr class="even">
<td><em>That’s what you get.</em></td>
<td>0.25</td>
<td><audio controls="" style="height:1.4em;width:160px"><source src="../../audio/ml/fn-10.wav" type="audio/wav"></audio></td>
</tr>
<tr class="odd">
<td><em>Uh,</em></td>
<td>0.00</td>
<td><audio controls="" style="height:1.4em;width:160px"><source src="../../audio/ml/fn-11.wav" type="audio/wav"></audio></td>
</tr>
<tr class="even">
<td><em>Thank you.</em></td>
<td>0.50</td>
<td><audio controls="" style="height:1.4em;width:160px"><source src="../../audio/ml/fn-12.wav" type="audio/wav"></audio></td>
</tr>
</tbody>
</table>
<p>The 23 false positives fall into two groups. The first consists of short, hallucination-typical phrases on segments where the audio may contain no intelligible speech — in which case the probe’s classification is arguably correct and the label is wrong:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Model output</th>
<th>Hallucinated token fraction</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><em>Thank you.</em></td>
<td>0.75</td>
<td><audio controls="" style="height:1.4em;width:160px"><source src="../../audio/ml/fp-04.wav" type="audio/wav"></audio></td>
</tr>
<tr class="even">
<td><em>Thank you.</em></td>
<td>0.75</td>
<td><audio controls="" style="height:1.4em;width:160px"><source src="../../audio/ml/fp-16.wav" type="audio/wav"></audio></td>
</tr>
<tr class="odd">
<td><em>Yeah.</em></td>
<td>0.67</td>
<td><audio controls="" style="height:1.4em;width:160px"><source src="../../audio/ml/fp-10.wav" type="audio/wav"></audio></td>
</tr>
</tbody>
</table>
<p>The second group are genuine probe errors, where real speech is present but in a form the probe has not encountered during training — synthetic or effects-processed game voices, song lyrics in background music, speech with heavy ambient noise or reverberation. All examples can be played back inline:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Model output</th>
<th>Hallucinated token fraction</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><em>Dance dance to the baby</em></td>
<td>1.00</td>
<td><audio controls="" style="height:1.4em;width:160px"><source src="../../audio/ml/fp-18.wav" type="audio/wav"></audio></td>
</tr>
<tr class="even">
<td><em>I’m not gonna do it!</em></td>
<td>1.00</td>
<td><audio controls="" style="height:1.4em;width:160px"><source src="../../audio/ml/fp-02.wav" type="audio/wav"></audio></td>
</tr>
<tr class="odd">
<td><em>Jump!</em></td>
<td>1.00</td>
<td><audio controls="" style="height:1.4em;width:160px"><source src="../../audio/ml/fp-21.wav" type="audio/wav"></audio></td>
</tr>
<tr class="even">
<td><em>Get him up!</em></td>
<td>1.00</td>
<td><audio controls="" style="height:1.4em;width:160px"><source src="../../audio/ml/fp-06.wav" type="audio/wav"></audio></td>
</tr>
<tr class="odd">
<td><em>WHAT THEY ARE?!</em></td>
<td>0.92</td>
<td><audio controls="" style="height:1.4em;width:160px"><source src="../../audio/ml/fp-13.wav" type="audio/wav"></audio></td>
</tr>
<tr class="even">
<td><em>Your top tower is under attack.</em></td>
<td>0.89</td>
<td><audio controls="" style="height:1.4em;width:160px"><source src="../../audio/ml/fp-12.wav" type="audio/wav"></audio></td>
</tr>
<tr class="odd">
<td><em>Take a picture of that.</em></td>
<td>0.86</td>
<td><audio controls="" style="height:1.4em;width:160px"><source src="../../audio/ml/fp-11.wav" type="audio/wav"></audio></td>
</tr>
<tr class="even">
<td><em>Get on the truck, let’s go! F</em>**ing normies! Eat this!*</td>
<td>0.77</td>
<td><audio controls="" style="height:1.4em;width:160px"><source src="../../audio/ml/fp-01.wav" type="audio/wav"></audio></td>
</tr>
<tr class="odd">
<td><em>We’ll be right back.</em></td>
<td>0.75</td>
<td><audio controls="" style="height:1.4em;width:160px"><source src="../../audio/ml/fp-03.wav" type="audio/wav"></audio></td>
</tr>
<tr class="even">
<td><em>I hit one of them, 40 white. His dude died on air by the other team.</em></td>
<td>0.71</td>
<td><audio controls="" style="height:1.4em;width:160px"><source src="../../audio/ml/fp-07.wav" type="audio/wav"></audio></td>
</tr>
<tr class="odd">
<td><em>Come on</em></td>
<td>0.67</td>
<td><audio controls="" style="height:1.4em;width:160px"><source src="../../audio/ml/fp-05.wav" type="audio/wav"></audio></td>
</tr>
<tr class="even">
<td><em>So here he is, you can see the…</em></td>
<td>0.64</td>
<td><audio controls="" style="height:1.4em;width:160px"><source src="../../audio/ml/fp-23.wav" type="audio/wav"></audio></td>
</tr>
<tr class="odd">
<td><em>Nope, I have not.</em></td>
<td>0.62</td>
<td><audio controls="" style="height:1.4em;width:160px"><source src="../../audio/ml/fp-15.wav" type="audio/wav"></audio></td>
</tr>
<tr class="even">
<td><em>And then it’s flying fire.</em></td>
<td>0.60</td>
<td><audio controls="" style="height:1.4em;width:160px"><source src="../../audio/ml/fp-14.wav" type="audio/wav"></audio></td>
</tr>
<tr class="odd">
<td><em>Quick hands.</em></td>
<td>0.60</td>
<td><audio controls="" style="height:1.4em;width:160px"><source src="../../audio/ml/fp-19.wav" type="audio/wav"></audio></td>
</tr>
<tr class="even">
<td><em>I’m gonna go see</em></td>
<td>0.57</td>
<td><audio controls="" style="height:1.4em;width:160px"><source src="../../audio/ml/fp-20.wav" type="audio/wav"></audio></td>
</tr>
<tr class="odd">
<td><em>Aw, stop it. If you guys like this video and you guys want to watch me try more fun Halloween hacks, I have a whole playlist.</em></td>
<td>0.57</td>
<td><audio controls="" style="height:1.4em;width:160px"><source src="../../audio/ml/fp-22.wav" type="audio/wav"></audio></td>
</tr>
<tr class="even">
<td><em>Sometimes you say, you hear it?</em></td>
<td>0.56</td>
<td><audio controls="" style="height:1.4em;width:160px"><source src="../../audio/ml/fp-09.wav" type="audio/wav"></audio></td>
</tr>
<tr class="odd">
<td><em>That feels like a tight fit.</em></td>
<td>0.50</td>
<td><audio controls="" style="height:1.4em;width:160px"><source src="../../audio/ml/fp-08.wav" type="audio/wav"></audio></td>
</tr>
<tr class="even">
<td><em>So</em></td>
<td>0.50</td>
<td><audio controls="" style="height:1.4em;width:160px"><source src="../../audio/ml/fp-17.wav" type="audio/wav"></audio></td>
</tr>
</tbody>
</table>
<p>There is a rough correspondence between the hallucinated token fraction and the intelligibility of the underlying audio: segments at the top of the table — non-legible crowd noises, heavily processed voices, shouted exclamations — are acoustically distant from conversational speech, and the probe’s confidence is accordingly high. Those at the bottom are altered or unusual in some way but remain clearly recognisable as speech, and the probe fires with correspondingly less certainty. It is worth noting that the probe was trained on only 3,000 examples per class, with no deliberate coverage of these corner cases. Performance on acoustically unusual speech — processed voices, background vocals, heavily reverberant or noise-overlapped audio — would likely improve with broader training data that includes such examples. The hallucination token fractions are higher for the energetic, exclamatory utterances at the top, which are acoustically the closest to hallucination-typical output. One observation from the token-level breakdown that is worth noting: in the first-group cases — short, stock phrases on borderline audio — both the prefix and a majority of the individual tokens tend to be classified as hallucinations. A classifier that requires the prefix to be hallucinated <em>and</em> a threshold fraction of the content tokens to be hallucinated would likely reduce false positives on legitimate speech while retaining sensitivity to genuine hallucinations. This was not pursued here, as the goal was to understand the mechanism rather than to optimise a detection method.</p>
</section>
<section id="where-the-signal-lives-cross-attention-not-generation" class="level3">
<h3 class="anchored" data-anchor-id="where-the-signal-lives-cross-attention-not-generation">Where the signal lives: cross-attention, not generation</h3>
<p>Evaluating the probe per individual token - rather than on the mean-pooled sequence - reveals something unexpected. For a subset of cases, every individual generated token is classified as <em>normal</em> by the probe, yet the overall mean-pooled activation is classified as a <em>hallucination</em>. Since the probe is a linear classifier, this can only happen if the mean is being pulled across the decision boundary by an activation not included in the per-token breakdown.</p>
<p>The culprit is the <strong>prefix activation</strong>: the decoder’s hidden state captured when it processes the initial <code>[BOS, LANG]</code> tokens before generating anything. This is the moment of the decoder’s first cross-attention over the encoder output - before a single transcript token exists. It is excluded from the per-token breakdown, but included in the mean.</p>
<p>A concrete example. A speech segment produces the output <em>“And,”</em> and the overall probe fires (false positive). The per-token breakdown looks like this:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Position</th>
<th>Token</th>
<th>Probe classification</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td><code>[prefix]</code></td>
<td>hallucination</td>
</tr>
<tr class="even">
<td>1</td>
<td><em>And</em></td>
<td>normal</td>
</tr>
<tr class="odd">
<td>2</td>
<td><em>,</em></td>
<td>normal</td>
</tr>
</tbody>
</table>
<p>The prefix is the only hallucination-classified position. Everything the decoder generated looks normal; only its initial state - set before generation begins, purely through cross-attention to the encoder - looks like a hallucination.</p>
<p>This tells us something about the nature of the undelrying mechanism here. The prefix activation is the decoder’s first and only opportunity to read the encoder output without any autoregressive context. Its state at that point is entirely determined by what the encoder produced - which is itself a near-perfect linear representation of speech vs non-speech. For non-speech audio, the encoder output sits deep in the non-speech cluster; the decoder’s initial cross-attention read of that output puts it in the hallucination region before any token is generated. For speech audio, the encoder output sits in the speech cluster; the initial cross-attention puts the decoder in the normal zone, and it stays there.</p>
<p>The implication is that the halucination signal in the decoder is encoded primarily in the <strong>initial cross-attention state</strong>, not in the autoregressive generation. The decoder does not become progressively more “aware” that it is hallucinating as it generates tokens - it knows from the very first step, before producing a single word, because it has already read the encoder’s non-speech representation. The tokens that follow are then generated from a starting point that already carries the hallucination signal in its mean-pooled representation. The cross-attention is the mechanism and everything else is downstream.</p>
</section>
<section id="ablation-ruling-out-sequence-length-confounds" class="level3">
<h3 class="anchored" data-anchor-id="ablation-ruling-out-sequence-length-confounds">Ablation: ruling out sequence-length confounds</h3>
<p>Two potential confounds are worth addressing. The first is <strong>transcript length</strong>: hallucinated transcripts are short (typically one to three words) while normal transcripts are long. The second is <strong>audio duration</strong>: silence segments used for the hallucination class may be systematically shorter than the speech segments, meaning the decoder’s cross-attention attends over a shorter encoder sequence - and the probe might be learning this length difference rather than anything about acoustic content.</p>
<p>Two ablations are run:</p>
<ul>
<li><strong>Transcript position</strong>: the probe is retrained using only the first word of each segment. At position 0, both classes are in the same place in the sequence; any remaining separation must come from cross-attention content.</li>
<li><strong>Audio duration</strong>: the probe is retrained using only segments whose natural duration falls within the overlap window between the two classes. Segments are used whole - not trimmed - to avoid the risk of cutting a speech segment down to a silent passage.</li>
</ul>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Full probe</th>
<th style="text-align: right;">First-word</th>
<th style="text-align: right;">Duration-matched</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">First layer</td>
<td style="text-align: right;">0.942</td>
<td style="text-align: right;">0.927</td>
<td style="text-align: right;">0.894</td>
</tr>
<tr class="even">
<td style="text-align: left;">Last layer</td>
<td style="text-align: right;">0.973</td>
<td style="text-align: right;">0.972</td>
<td style="text-align: right;">0.969</td>
</tr>
</tbody>
</table>
<p>The first-word probe barely moves - consistent with the positional confound being structurally implausible in any case, since the primary signal carrier is the prefix activation, computed before any token exists. Duration matching causes a ~5 percentage point drop in the first layer, suggesting the earliest decoder layer is somewhat sensitive to encoder sequence length; by the final layer the gap has closed to under half a point as deeper cross-attention integration takes over. Both ablations confirm that the separation is primarily grounded in acoustic content.</p>
</section>
</section>
<section id="interpretation" class="level2">
<h2 class="anchored" data-anchor-id="interpretation">Interpretation</h2>
<p>The decoder builds its own independent representation distinguishing hallucination from normal transcription, to essentially the same accuracy as the encoder probe. The model does not merely process non-speech audio differently in the encoder - it also generates tokens differently when hallucinating. Its internal state during hallucination generation is linearly distinguishable from its state during real transcription, consistently, across all eight decoder layers, with no learning beyond a logistic regression.</p>
<p>This means the model has <strong>redundant, multilayerd knowledge that it is hallucinating</strong>. We show that the encoder has it from layer 0 and that the decoder builds it from generation step 1, but neither representation surfaces in the output.</p>
<p>The suppression achieved by encoder-level steering works not because it introduces new information into the system, but because it amplifies a signal the model already possesses. The decoder probe shows the complementary side of this: the decoder would, if it had a way to act on its own internal state, be capable of flagging its output as hallucinated.</p>
<p>The information required to suppress hallucinations is present in the model twice over - once at the input stage, once at the output stage. What is absent is not a training signal - non-speech and sparse-speech data were included in training, and the model does produce silence in the typical case. What is absent is a training objective that explicitly rewards the model for routing through the latent representation the probe identifies. The coupling between its internal knowledge that it is hallucinating and the decision to output EOS is loose enough to fail at the margin.</p>
<p>A secondary finding worth noting: the decoder probe is precise enough to function as an approximate label auditor. Applied to a labelled dataset, it surfaces samples where the label and the audio content disagree. This is not its intended use, but it suggests that interpretability tools applied at the output-generation stage can detect annotation noise that are otherwise challenging to identify.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>